<?php

namespace Database\Seeders;

use App\Models\ProductModel;
use Illuminate\Database\Seeder;

class ProductDescriptionSeeder extends Seeder
{
    public function run(): void
    {
        $descriptions = [
            ['artist' => 'Fleetwood Mac', 'album_title' => 'Rumours', 'description' => 'Rumours es el undécimo álbum de estudio de la banda británica de rock Fleetwood Mac, publicado en 1977 por Warner Bros. Records. Las sesiones estuvieron marcadas por los conflictos personales entre los músicos y el consumo abusivo de cocaína. Las letras tratan sobre relaciones personales, a menudo tumultuosas; en cierto modo, un reflejo de lo que pasaba al interior de la banda.'],
            ['artist' => 'Berliner Philharmoniker', 'album_title' => 'Beethoven: Symphony No. 9', 'description' => 'La Sinfonía n.º 9 en re menor, op. 125, conocida como Coral, es una sinfonía coral compuesta por Ludwig van Beethoven entre 1822 y 1824. Se estrenó en Viena el 7 de mayo de 1824. Muchos críticos y musicólogos la consideran como una obra maestra de la música clásica occidental y uno de los logros supremos de toda la historia de la música.'],
            ['artist' => 'The Beatles', 'album_title' => 'Abbey Road', 'description' => 'Abbey Road es el duodécimo álbum de estudio de la banda de rock The Beatles. Fue publicado en el Reino Unido el 26 de septiembre de 1969 por Apple Records. Las grabaciones comenzaron el 22 de febrero de 1969, lo que lo convierte en el último trabajo registrado por el grupo antes de su separación, aunque Let It Be (1970) se había grabado con anterioridad.'],
            ['artist' => 'David Bowie', 'album_title' => 'Ziggy Stardust', 'description' => 'The Rise and Fall of Ziggy Stardust and the Spiders from Mars, conocido simplemente como Ziggy Stardust, es el quinto álbum de estudio y primer álbum conceptual de David Bowie, publicado en 1972. Fue el disco con el que consiguió llegar a las grandes audiencias y está considerado uno de los más representativos del glam rock.'],
            ['artist' => 'James Brown', 'album_title' => 'Live at the Apollo', 'description' => 'Live at the Apollo es un álbum en directo del músico estadounidense James Brown, grabado el 24 de octubre de 1962 en el Apollo Theater de Nueva York. Considerado uno de los mejores álbumes en directo de la historia de la música.'],
            ['artist' => "What's Going On", 'album_title' => "What's Going On", 'description' => ''],
            ['artist' => 'Marvin Gaye', 'album_title' => "What's Going On", 'description' => "What's Going On es el undécimo álbum de estudio del cantante estadounidense de soul Marvin Gaye, lanzado el 21 de mayo de 1971. Con letras intimistas acerca del abuso de drogas, la destrucción del medio ambiente, la pobreza y la guerra de Vietnam, el álbum fue una sensación inmediata y ha permanecido como un clásico del soul."],
            ['artist' => 'Carlos Santana', 'album_title' => 'Abraxas', 'description' => 'Abraxas es el segundo álbum de estudio de la banda de rock estadounidense Santana, publicado por Columbia Records el 23 de septiembre de 1970. Contiene canciones icónicas como Black Magic Woman y Samba pa ti.'],
            ['artist' => 'Daft Punk', 'album_title' => 'Random Access Memories', 'description' => 'Random Access Memories es el cuarto y último álbum de estudio del dúo francés Daft Punk, publicado el 21 de mayo de 2013 bajo licencia de Daft Life. La grabación comenzó cuando el dúo preparaba la banda sonora de la película Tron: Legacy.'],
            ['artist' => 'Obituary', 'album_title' => 'Slowly We Rot', 'description' => 'Slowly We Rot es el primer disco de estudio de la banda death metal Obituary, considerado su trabajo más rápido, pesado y brutal. Es una de las primeras muestras del death metal junto a otros trabajos de Possessed, Death, Morbid Angel y Napalm Death. Fue editado en 1989 y relanzado en 1997 por Roadrunner Records.'],
            ['artist' => 'John Coltrane', 'album_title' => 'A Love Supreme', 'description' => 'A Love Supreme es un álbum de jazz grabado por el cuarteto de John Coltrane el 9 de diciembre de 1964. El disco es una suite en cuatro partes: Acknowledgement, Resolution, Pursuance y Psalm. Fue concebido como un disco espiritual, representativo de una búsqueda personal de pureza por parte de Coltrane.'],
            ['artist' => 'Possessed', 'album_title' => 'Seven Churches', 'description' => 'Seven Churches es el álbum debut del grupo Possessed lanzado en 1985. El título del álbum se refiere a las Siete iglesias de Asia mencionadas en el libro del Apocalipsis. Está incluido en las listas de los «10 esenciales discos del death metal».'],
            ['artist' => 'Cryptopsy', 'album_title' => 'None So Vile', 'description' => 'Cryptopsy es una influyente banda de metal proveniente de Montreal, Canadá, formada en 1988 por Lord Worm (vocalista), Jon Levasseur (guitarra), Steve Thibault (bajo) y Flo Mounier (batería). A lo largo de los años la alineación ha cambiado varias veces, pero Flo Mounier ha sido una constante.'],
            ['artist' => 'Death', 'album_title' => 'Symbolic', 'description' => 'Symbolic es el sexto álbum de estudio de la banda estadounidense de death metal Death. Se puede apreciar un fuerte contenido melódico contrastando con la fuerza y velocidad del death metal más crudo, así como un cambio de sonido en la voz de Chuck hacia un tono más agudo.'],
            ['artist' => 'Bill Evans', 'album_title' => 'Waltz for Debby', 'description' => '«Waltz for Debby» es un estándar de jazz compuesto por el pianista estadounidense Bill Evans. Se grabó por primera vez en su álbum de 1956 New Jazz Conceptions, y más tarde en su álbum en vivo homónimo de 1962.'],
            ['artist' => 'Napalm Death', 'album_title' => 'Scum', 'description' => 'Scum es el álbum debut de la banda grindcore británica Napalm Death, lanzado el 1 de julio de 1987.'],
            ['artist' => 'Aphex Twin', 'album_title' => 'Selected Ambient Works 85–92', 'description' => 'Selected Ambient Works 85-92 es el álbum de estudio debut de Aphex Twin, seudónimo del productor británico Richard David James. Fue lanzado el 9 de noviembre de 1992 a través de Apollo Records y consta de pistas de ambient techno supuestamente grabadas desde 1985, cuando James tenía catorce años.'],
            ['artist' => 'Led Zeppelin', 'album_title' => 'IV', 'description' => 'Led Zeppelin IV es el cuarto álbum de estudio de la banda británica Led Zeppelin, publicado en noviembre de 1971 por Atlantic Records. Considerado uno de los mejores discos de rock de la historia, incluye canciones icónicas como Black Dog, Rock and Roll y Stairway to Heaven.'],
            ['artist' => 'Celia Cruz', 'album_title' => 'La Negra Tiene Tumbao', 'description' => 'La negra tiene tumbao es el 59.º álbum de estudio grabado por la artista cubano-estadounidense Celia Cruz. Fue lanzado bajo el sello discográfico Sony Discos el 30 de octubre de 2001.'],
            ['artist' => 'Morbid Angel', 'album_title' => 'Altars of Madness', 'description' => 'Altars of Madness es el álbum debut de la banda de death metal Morbid Angel, establecida en Florida. En 2006 se lanzó un doble disco con la remasterización del 2003 y el Live Madness 89, grabado en el Nottingham Rock City el 14 de noviembre de 1989.'],
            ['artist' => 'Suffocation', 'album_title' => 'Effigy of the Forgotten', 'description' => 'Effigy of the Forgotten es el álbum debut de la banda de death metal Suffocation, lanzado en 1991. Considerado como uno de los álbumes más innovadores dentro del death metal, ha servido de inspiración para varias bandas.'],
            ['artist' => 'Repulsion', 'album_title' => 'Horrified', 'description' => 'Repulsion es una banda estadounidense de grindcore de Flint, Michigan, fundada en 1984 por Scott Carlson y Matt Olivo. La banda pasó por varios cambios de nombre antes de establecerse como Repulsion tras la marcha de Carlson y Olivo de Death a mediados de los 80. Grabaron su álbum debut Horrified en 1986, publicándolo tres años después. La banda ha sido citada como influencia por grupos como Cannibal Corpse y Napalm Death.'],
            ['artist' => 'Boards of Canada', 'album_title' => 'Music Has the Right to Children', 'description' => 'Music has the right to children es un álbum del grupo IDM británico Boards of Canada, lanzado el 20 de abril de 1998 en Europa.'],
            ['artist' => 'Dying Fetus', 'album_title' => 'Destroy the Opposition', 'description' => 'Dying Fetus es una banda estadounidense de death metal formada en 1991 en Annapolis, Maryland. A partir del 2008, está formada por John Gallagher, Sean Beasley y Trey Williams.'],
            ['artist' => 'Terrorizer', 'album_title' => 'World Downfall', 'description' => 'World Downfall es el álbum debut de la banda estadounidense de grindcore Terrorizer, lanzado por Earache Records el 13 de noviembre de 1989.'],
            ['artist' => 'The Kill', 'album_title' => 'Kill Them... All', 'description' => 'The Kill fue una banda de grindcore de Melbourne, Australia, formada en el año 2000. Con letras que trataban sobre violencia, estupidez y humor, publicaron su música bajo el sello Blastasfuk Grindcore hasta su separación.'],
            ['artist' => 'Brutal Truth', 'album_title' => 'Extreme Conditions Demand Extreme Responses', 'description' => 'Brutal Truth fue un supergrupo estadounidense de Grindcore y Deathgrind de Nueva York, formado en 1990 por exmiembros de Anthrax, Nuclear Assault, Stormtroopers Of Death y Siege. La banda se separó en 1998, volvió a unirse en 2006 y anunció su separación definitiva en 2014.'],
            ['artist' => 'Nirvana', 'album_title' => 'Nevermind', 'description' => 'Nevermind es el segundo álbum de estudio de la banda estadounidense de grunge Nirvana, publicado el 24 de septiembre de 1991. Producido por Butch Vig, fue el primer lanzamiento de la banda con DGC Records. Gracias a este álbum el género grunge se hizo conocido a nivel mundial y es considerado uno de los mejores de la historia.'],
            ['artist' => 'Sickrecy', 'album_title' => 'Salvation Through Tyranny', 'description' => 'Sickrecy es una banda de grindcore de Suecia, activa desde 2021 y actualmente firmada con Selfmadegod Records.'],
            ['artist' => 'Party Cannon', 'album_title' => 'Partied in Half', 'description' => 'Party Cannon es una banda de slam death metal de Dunfermline, Escocia, formada en 2010.'],
            ['artist' => 'A Tribe Called Quest', 'album_title' => 'The Low End Theory', 'description' => 'The Low End Theory es el segundo álbum del grupo estadounidense de hip hop A Tribe Called Quest, publicado el 24 de septiembre de 1991 por Jive Records. Fue producido por el grupo y Skeff Anselm, especialmente por el miembro Q-Tip.'],
            ['artist' => 'Jenovavirus', 'album_title' => 'Jenovavirus', 'description' => 'Jenovavirus fue una banda experimental de slam/brutal death metal de Onojo/Fukuoka, Japón, activa entre 2005 y 2006 bajo el sello Revenge Productions. Tenían previsto lanzar un álbum completo de 13 canciones, pero se disolvieron antes de poder grabarlo.'],
            ['artist' => 'Gorilla Biscuits', 'album_title' => 'Start Today', 'description' => 'Start Today es el segundo y último álbum de la banda de hardcore punk Gorilla Biscuits, lanzado en 1989 por Revelation Records. Además, fue publicado en Alemania por el sello We Bite.'],
            ['artist' => 'Gorguts', 'album_title' => 'Considered Dead', 'description' => 'Considered Dead es el álbum debut del grupo canadiense de death metal técnico Gorguts.'],
            ['artist' => 'Judge', 'album_title' => "Bringin' It Down", 'description' => "Bringin' It Down es el álbum debut de la banda de hardcore neoyorquina Judge, publicado en 1989 por Revelation Records. Considerado uno de los discos fundamentales del hardcore de finales de los 80."],
            ['artist' => 'Necrophagia', 'album_title' => 'The Divine Art of Torture', 'description' => 'Necrophagia fue una banda de death metal fundada en 1983, siendo una de las primeras en su género. Su idea era sonar como Regan de El exorcista, o mucho peor. El nacimiento de Necrophagia comienza con la inspiración de Killjoy y su obsesión por el horror, con influencias como Venom y Hellhammer.'],
            ['artist' => 'Brodequin', 'album_title' => 'Harbinger of Woe', 'description' => 'Brodequin es una banda estadounidense de death metal de Knoxville, Tennessee. Formada en 1998 por los hermanos Mike y Jamie Bailey, la banda ha lanzado cuatro álbumes y dos EPs, siendo Harbinger of Woe, publicado en 2024, su lanzamiento más reciente.'],
            ['artist' => 'Nile', 'album_title' => 'Amongst the Catacombs of Nephren-Ka', 'description' => 'Nile es una banda de death metal formada en 1993 procedente de Carolina del Sur, Estados Unidos. La letra de las canciones está inspirada en leyendas, religión y arte del Antiguo Egipto y Mesopotamia.'],
            ['artist' => 'Deeds of Flesh', 'album_title' => 'Path of the Weakening', 'description' => 'Deeds of Flesh es una banda de brutal death metal originaria de Los Osos, San Luis Obispo, California, formada en 1994.'],
            ['artist' => 'M.C.D.', 'album_title' => 'De Ningún Sitio a Ninguna Parte', 'description' => 'M.C.D. es un grupo de punk español procedente de Bilbao, formado en 1979 tras la explosión musical ocurrida en el Reino Unido a mediados y finales de los años 1970.'],
            ['artist' => 'Misery Index', 'album_title' => 'Discordia', 'description' => 'Discordia es el segundo álbum de estudio de la banda estadounidense de death metal Misery Index, lanzado en 2006.'],
            ['artist' => 'Dismember', 'album_title' => 'Like an Ever Flowing Stream', 'description' => 'Dismember es una banda sueca de death metal formada en 1988 en Estocolmo, Suecia.'],
            ['artist' => 'Slayer', 'album_title' => 'Seasons in the Abyss', 'description' => 'Seasons in the Abyss es el quinto álbum de estudio de la banda estadounidense de thrash metal Slayer, grabado y lanzado en 1990 por Def American Records. Fue también el último álbum con el baterista original Dave Lombardo.'],
            ['artist' => 'Nuclear Assault', 'album_title' => 'Game Over', 'description' => 'Game Over es el álbum debut de la banda de thrash metal Nuclear Assault, lanzado en 1986 por Combat Records. Fue bien recibido por fans y críticos y la banda salió de gira rápidamente.'],
            ['artist' => 'Disconformity', 'album_title' => 'Depravation of Stigma', 'description' => 'Disconformity es una banda japonesa de slam/brutal death metal formada en noviembre de 2002 por Keisuke, Kazz y Yu-Ki. La banda aparece en el documental Japan Extreme Metal con entrevistas y fragmentos de actuaciones en directo.'],
            ['artist' => 'Miles Davis', 'album_title' => 'Kind of Blue', 'description' => 'Kind of Blue es un álbum de estudio del músico estadounidense de jazz Miles Davis editado en agosto de 1959.'],
            ['artist' => 'Radiohead', 'album_title' => 'OK Computer', 'description' => 'OK Computer es el tercer álbum de estudio de la banda británica de rock alternativo Radiohead, lanzado el 21 de mayo de 1997. En él se observan letras abstractas, un sonido denso con varias capas e influencias eclécticas, lo cual sentó las bases para el trabajo posterior del grupo, más experimental.'],
            ['artist' => 'Cannibal Corpse', 'album_title' => 'Tomb of the Mutilated', 'description' => 'Tomb of The Mutilated es el tercer álbum de estudio de Cannibal Corpse, publicado el 22 de septiembre de 1992 a través de Metal Blade Records. Es considerado por la crítica como la obra maestra de Cannibal Corpse y uno de los mejores dentro del death metal.'],
            ['artist' => 'The Velvet Underground', 'album_title' => 'The Velvet Underground & Nico', 'description' => 'The Velvet Underground & Nico es el primer álbum de estudio de la banda estadounidense de rock The Velvet Underground, lanzado en 1967 con la colaboración de la cantante alemana Nico. Fue grabado en Nueva York y Hollywood entre abril y mayo de 1966 bajo la dirección de Andy Warhol.'],
            ['artist' => 'Pink Floyd', 'album_title' => 'The Dark Side of the Moon', 'description' => 'The Dark Side of the Moon es el octavo álbum de estudio de la banda de rock progresivo Pink Floyd, lanzado el 1 de marzo de 1973 por Harvest Records. Fue concebido como un álbum conceptual sobre las presiones del estilo de vida de la banda y los problemas de salud mental del exmiembro Syd Barrett.'],
            ['artist' => 'Origin', 'album_title' => 'Antithesis', 'description' => 'Origin es una banda estadounidense de death metal técnico de Topeka, Kansas, fundada en 1990. Han sido reconocidos por combinar un sonido áspero con un alto nivel de habilidad técnica y virtuosismo.'],
            ['artist' => 'Bathory', 'album_title' => 'Blood Fire Death', 'description' => 'Blood Fire Death es el cuarto álbum de la banda de black metal y viking metal sueco Bathory. Es considerado por muchos fanáticos como la obra maestra de la banda y pieza clave de la primera oleada del black metal junto con discos como To Mega Therion, Melissa y Black Metal de Venom.'],
            ['artist' => 'Blunt Force Trauma', 'album_title' => 'Vengeance for Nothing', 'description' => 'Banda de brutal death metal de Osaka, Japón, formada en 2006.'],
            ['artist' => 'Carcass', 'album_title' => 'Necroticism: Descanting the Insalubrious', 'description' => 'Necroticism - Descanting the Insalubrious es el tercer álbum de estudio de la banda inglesa de metal extremo Carcass, lanzado en 1991 por Earache Records. Es el primer álbum de la banda en el que participa el guitarrista sueco Michael Amott.'],
            ['artist' => 'Metallica', 'album_title' => 'Ride the Lightning', 'description' => 'Ride the Lightning es el segundo álbum de estudio de Metallica, publicado el 27 de julio de 1984 a través de Megaforce Records. Grabado en Copenhague bajo la producción de Flemming Rasmussen, el título proviene de una referencia en la novela Apocalipsis de Stephen King.'],
            ['artist' => 'Bolt Thrower', 'album_title' => 'The IVth Crusade', 'description' => 'Bolt Thrower fue una banda británica de death metal de Coventry, Inglaterra. Formados en 1986, pasaron de Vinyl Solution a Earache Records y luego a Metal Blade Records. A lo largo de sus 30 años de carrera lanzaron ocho álbumes de estudio.'],
            ['artist' => 'Mortal Decay', 'album_title' => 'Forensic', 'description' => 'Mortal Decay es una mítica banda de Audubon, Nueva Jersey, fundada en 1991 por Anthony Ipri, Anthony DiVigenze y John Paoline. Su estilo es un técnico, aplastante y brutal death metal similar a Internal Bleeding o Suffocation. Forensic, lanzado en 2002 por Unique Leader Records, es considerado su obra cumbre.'],
            ['artist' => 'Death Toll 80K', 'album_title' => 'Harsh Realities', 'description' => 'Death Toll 80K es una banda de grindcore/death metal de Lappeenranta, Finlandia, activa desde 2005. Sus letras abordan el antimilitarismo, el medioambiente y la crítica social, actualmente bajo el sello Svart Records.'],
        ];

        foreach ($descriptions as $data) {
            ProductModel::where('artist', $data['artist'])
                ->where('album_title', $data['album_title'])
                ->update(['description' => $data['description']]);
        }
    }
}
